#kubectl http://mirror.azure.cn/kubernetes/kubectl/
# kustomize  https://github.com/kubernetes-sigs/kustomize/tags



FROM registry.cn-chengdu.aliyuncs.com/leagders/kubectl:v1.20.8-kustomize

ADD kubectl /usr/local/bin/

RUN chmod +x /usr/local/bin/kubectl
